package com.redhat.gpte.training;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2019-04-02T00:29:06.245-03:00
 * Generated source version: 3.2.5
 *
 */
@WebService(targetNamespace = "http://training.gpte.redhat.com/", name = "CustomerService")
@XmlSeeAlso({ObjectFactory.class})
public interface CustomerService {

    @WebMethod(action = "http://training.gpte.redhat.com/getAllCustomers")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getAllCustomersResponse", targetNamespace = "http://training.gpte.redhat.com/", partName = "parameters")
    public GetAllCustomersResponse getAllCustomers();

    @WebMethod(action = "http://training.gpte.redhat.com/saveCustomer")
    @RequestWrapper(localName = "saveCustomer", targetNamespace = "http://training.gpte.redhat.com/", className = "com.redhat.gpte.training.SaveCustomer")
    @ResponseWrapper(localName = "saveCustomerResponse", targetNamespace = "http://training.gpte.redhat.com/", className = "com.redhat.gpte.training.SaveCustomer")
    public void saveCustomer(
        @WebParam(mode = WebParam.Mode.INOUT, name = "customer", targetNamespace = "")
        javax.xml.ws.Holder<Customer> customer
    );

    @WebMethod(action = "http://training.gpte.redhat.com/getCustomerByName")
    @RequestWrapper(localName = "getCustomerByName", targetNamespace = "http://training.gpte.redhat.com/", className = "com.redhat.gpte.training.GetCustomerByName")
    @ResponseWrapper(localName = "getCustomerByNameResponse", targetNamespace = "http://training.gpte.redhat.com/", className = "com.redhat.gpte.training.GetCustomerByNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.redhat.gpte.training.Customer> getCustomerByName(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name
    ) throws NoSuchCustomerException;
}
