package com.redhat.gpte.training;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2019-04-02T00:29:06.261-03:00
 * Generated source version: 3.2.5
 *
 */
@WebServiceClient(name = "CustomerService",
                  wsdlLocation = "file:/home/juan/Dev/ACCSA/fuse_camel/camel-labs/5_Components/camel-webservice/src/main/resources/wsdl/CustomerService.wsdl",
                  targetNamespace = "http://training.gpte.redhat.com/")
public class CustomerService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://training.gpte.redhat.com/", "CustomerService");
    public final static QName CustomerServicePort = new QName("http://training.gpte.redhat.com/", "CustomerServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/juan/Dev/ACCSA/fuse_camel/camel-labs/5_Components/camel-webservice/src/main/resources/wsdl/CustomerService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CustomerService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/home/juan/Dev/ACCSA/fuse_camel/camel-labs/5_Components/camel-webservice/src/main/resources/wsdl/CustomerService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CustomerService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CustomerService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CustomerService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CustomerService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CustomerService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CustomerService
     */
    @WebEndpoint(name = "CustomerServicePort")
    public CustomerService getCustomerServicePort() {
        return super.getPort(CustomerServicePort, CustomerService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerService
     */
    @WebEndpoint(name = "CustomerServicePort")
    public CustomerService getCustomerServicePort(WebServiceFeature... features) {
        return super.getPort(CustomerServicePort, CustomerService.class, features);
    }

}
