
package com.redhat.gpte.training;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.5
 * 2019-04-02T00:29:06.204-03:00
 * Generated source version: 3.2.5
 */

@WebFault(name = "NoSuchCustomer", targetNamespace = "http://training.gpte.redhat.com/")
public class NoSuchCustomerException extends Exception {

    private com.redhat.gpte.training.NoSuchCustomer noSuchCustomer;

    public NoSuchCustomerException() {
        super();
    }

    public NoSuchCustomerException(String message) {
        super(message);
    }

    public NoSuchCustomerException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public NoSuchCustomerException(String message, com.redhat.gpte.training.NoSuchCustomer noSuchCustomer) {
        super(message);
        this.noSuchCustomer = noSuchCustomer;
    }

    public NoSuchCustomerException(String message, com.redhat.gpte.training.NoSuchCustomer noSuchCustomer, java.lang.Throwable cause) {
        super(message, cause);
        this.noSuchCustomer = noSuchCustomer;
    }

    public com.redhat.gpte.training.NoSuchCustomer getFaultInfo() {
        return this.noSuchCustomer;
    }
}
